### ISSUE TITLE
❓懒加载模块引出的若干问题

### ISSUE THREAD

**Issue by NewsFun** [NewsFun/blog#2]
## 前言

懒加载模块在网站开发中是一种常用的优化手段，通常做法是监听滚动条，判断数据框是否到达某个位置，然后触发数据加载方法。

说实在的这个功能写过很多次了，然而都没有总结一下，这次趁周末加班时间，整理一下两天来的成果和踩坑结论。

通常懒加载的代码都是固定的，以下代码为项目代码，可放心食用。如有不良反应，请及时反馈。

## 懒加载常用代码

页面结构如下：

```html
<ul class="list">
    <li class="item"></li>
    <li class="item"></li>
    <li class="item"></li>
    <!-- .... -->
</ul>
```

样式如下：

```css
.list{
    width: 100%;
    height: 100%;
    overflow: auto; /*important*/
}
.item{
    width: 100%;
    height: 50px;
}
```

代码如下：

```javascript
function ajax(){
    //code here
}
```

```javascript
funciton lazyLoad(param){
    let callback = param.callback
    let box = param.scrollBox
    let data = param.scroller
    let time = param.time

    box.addEventListener('scroll', (e) => {
        let th = data.offsetHeight
        let bh = box.offsetHeight
        let bst = box.scrollTop
        let btm = th - bh - bst
        if (btm < 100 && callback) {
            callback()
        }
    })
}
```

## 问题

1. 无法监听到滚动事件

2. 懒加载被多次触发

暂时想到的就这么多，如果以后还有问题，继续补充。
